FROM registry.stage.redhat.io/rhel10/rhel-bootc:10.0

ARG FIRSTBOOTPROFILE=ssc600

# prep for RHEL10 beta
RUN sed -i 's/enabled=1/enabled=0/' /etc/yum/pluginconf.d/subscription-manager.conf
COPY redhat.repo /etc/yum.repos.d/redhat.repo

# kernel-rt deploy
RUN dnf remove -y kernel-{core,modules} && dnf install -y kernel-rt

# various required packages
RUN dnf install -y intel-cmt-cat libvirt libvirt-daemon qemu-kvm libvirt-client-qemu virt-install linuxptp && dnf clean all

# add tuned custom profile
RUN mkdir -p /etc/tuned/ssc600
COPY ssc600_tuned_profile/tuned.conf /etc/tuned/ssc600
COPY ssc600_tuned_profile/ssc600-setup.sh /etc/tuned/ssc600
RUN echo 'kargs = ["default_hugepagesz=1GB","idle=poll","intel.max_cstate=0","intel_idle.max_cstate=0","processor.max_cstate=0","processor_idle.max_cstate=0","intel_pstate=disable","rdt=cmt,l3cat,l3cdp,mba","iomem=relaxed","intel_iommu=on","iommu=pt","selinux=0","audit=0","ipv6.disable=0"]' > /usr/lib/bootc/kargs.d/00-abb.toml

# add firstboot systemd service
RUN echo "FIRSTBOOTPROFILE=${FIRSTBOOTPROFILE}" > /etc/default/tuned-profile-firstboot
COPY systemd/bootc-tuned-firstboot.service /etc/systemd/system/bootc-tuned-firstboot.service
RUN systemctl enable bootc-tuned-firstboot.service

# add PTP sync script and service
COPY systemd/ptp_status.service /etc/systemd/system/ptp_status.service
COPY scripts/ptp_status.sh /usr/sbin/ptp_status.sh
RUN chmod 755 /usr/sbin/ptp_status.sh && systemctl enable ptp_status.service

# qemu hook
RUN mkdir -p /etc/libvirt/hooks/qemu
COPY scripts/qemu.hook /etc/libvirt/hooks/qemu/qemu.hook
RUN chmod 755 /etc/libvirt/hooks/qemu/qemu.hook

# checks and balances
RUN bootc container lint
