FROM registry.redhat.io/rhel10/rhel-bootc

ARG FIRSTBOOTPROFILE=vpac

# kernel-rt deploy
RUN dnf remove -y kernel-{core,modules} && dnf install -y kernel-rt

# various required packages
RUN dnf install -y intel-cmt-cat libvirt libvirt-daemon qemu-kvm libvirt-client-qemu virt-install linuxptp tuned-profiles-realtime tuned-profiles-nfv && dnf clean all

# add tuned custom profile
RUN mkdir -p /etc/tuned/profiles/vpac
COPY vpac_tuned_profile/tuned.conf /etc/tuned/profiles/vpac
COPY vpac_tuned_profile/vpac-setup.sh /etc/tuned/profiles/vpac
RUN echo 'kargs = ["default_hugepagesz=1GB","idle=poll","intel.max_cstate=0","intel_idle.max_cstate=0","processor.max_cstate=0","processor_idle.max_cstate=0","intel_pstate=disable","rdt=cmt,l3cat,l3cdp,mba","iomem=relaxed","intel_iommu=on","iommu=pt","selinux=0","audit=0","ipv6.disable=0"]' > /usr/lib/bootc/kargs.d/00-vpac.toml

# add firstboot systemd service
RUN echo "FIRSTBOOTPROFILE=${FIRSTBOOTPROFILE}" > /etc/default/tuned-profile-firstboot
COPY systemd/bootc-tuned-firstboot.service /etc/systemd/system/bootc-tuned-firstboot.service
RUN systemctl enable bootc-tuned-firstboot.service

# add PTP sync script and service
COPY systemd/vpac-ptp-status.service /etc/systemd/system/vpac-ptp-status.service
COPY scripts/vpac-ptp-status.sh /usr/sbin/vpac-ptp-status.sh
RUN chmod 755 /usr/sbin/vpac-ptp-status.sh && systemctl enable vpac-ptp-status.service && mkdir -p /var/ptp
COPY etc/timemaster.conf /etc/timemaster.conf

# qemu hook
RUN mkdir -p /etc/libvirt/hooks/qemu
COPY scripts/qemu.hook /etc/libvirt/hooks/qemu/qemu.hook
RUN chmod 755 /etc/libvirt/hooks/qemu/qemu.hook

# disable irqbalance
RUN systemctl disable irqbalance

# checks and balances
RUN bootc container lint

