[main]
summary = Red Hat VPAC
include = realtime-virtual-host

[script]
script=${i:PROFILE_DIR}/vpac-setup.sh

[bootloader]
cmdline_vpac=+default_hugepagesz=1GB idle=poll intel.max_cstate=0 intel_idle.max_cstate=0 processor.max_cstate=0 processor_idle.max_cstate=0 intel_pstate=disable rdt=cmt,l3cat,l3cdp,mba iomem=relaxed intel_iommu=on iommu=pt selinux=0 audit=0 ipv6.disable=0

[sysctl]
kernel.nmi_watchdog = 0
kernel.sched_rt_runtime_us = -1
vm.nr_hugepages = 10
