[ptp_domain 0]
interfaces vpac-rt
ptp4l_option network_transport L2

[timemaster]
ntp_program chronyd

[chrony.conf]
makestep 1.0 3
rtcsync
driftfile /var/lib/chrony/drift
ntsdumpdir /var/lib/chrony

[ntp.conf]

[ptp4l.conf]

[chronyd]
path /usr/sbin/chronyd

[ntpd]
path /usr/sbin/ntpd
options -u ntp:ntp -g

[phc2sys]
path /usr/sbin/phc2sys
options -l 5

[ptp4l]
path /usr/sbin/ptp4l
options -l 5 -A --clientOnly=1 --step_threshold=0.1
